### ISSUE TITLE
Variation image bug.

### ISSUE THREAD

**Issue by deanoakley** [thriveweb/wooswipe#27]
1. Add variation images to products 
2. Select a variation that changes the large image.
3. Then the product variation image showing in slider popup is wrong

**Comment by vguns** [comment]
Is there a solution to this problem?

**Comment by deanoakley** [comment]
I do plan on catching up on these issues soon!

**Comment by morris4ever69** [comment]
Is there any update (fix) for this? Thanks.

**Comment by timtamimi** [comment]
Hi there. I note this issue has been closed by #32, but I'm not sure the issue is fixed (I could be wrong).

FYI I tested with:

```
Woocommerce 4.2.2
WooCommerce Additional Variation Images 1.7.23
WooCommerce Variation Swatches and Photos 3.1.1
Wordpress 5.4.2
```

...and found that when I enabled Wooswipe, the issue of images not filtering down to the correct variation galleryset appeared. I disabled Wooswipe, and functionality returned to normal.

**Comment by kurtisbradley** [comment]
@timtamimi We added compatibility with WooCommerce Variation Swatches and Photos. 

Can you please download the latest repo to test if the issue is still on your site?

**Comment by timtamimi** [comment]
> @timtamimi We added compatibility with WooCommerce Variation Swatches and Photos.
> 
> Can you please download the latest repo to test if the issue is still on your site?

Thanks for looking into it!

Unfortunately there's no change.

Replication steps:
- Created a product, with two colour variations.
- Ensured that it works sans-Wooswipe
- Downloaded a copy of master, up to and including commit d7323ac
- Added to /plugins
- Activated the plugin


Environment is still the same:
```
Woocommerce 4.2.2
WooCommerce Additional Variation Images 1.7.23
WooCommerce Variation Swatches and Photos 3.1.1
Wordpress 5.4.2
```

A couple of observations:

- The plugins page lists the plugin as being v1.8.7 not 1.8.8. But I assume this is because WP is pulling the plugin metadata from the Wordpress plugins system, not from Github, so I assume this is not relevant.

- The default gallery loads fine. Changing colours/variations does not in any way change the gallery images.

**Comment by kurtisbradley** [comment]
Thanks for checking that out.

When I first read your comment, since it was posted on this issue, I though it was related and that it was the swatch plugin making the popup image be wrong. 

But rereading your issue it has to do with not filtering the gallery when a variation is set. Which has to do with the Additional Variation Images plugin.

That was my mistake. Maybe in the future we will look at compatibility with WooCommerce Additional Variation Images.
